"""Table added

Revision ID: 203f6af8fdfa
Revises:
Create Date: 2022-12-13 12:58:56.242851

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = "203f6af8fdfa"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("gender", sa.String(), nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), nullable=True),
        sa.Column("is_deleted", sa.BOOLEAN(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True, default=datetime.utcnow),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True, default=datetime.utcnow),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "competitions",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), nullable=True),
        sa.Column("is_deleted", sa.BOOLEAN(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True, default=datetime.utcnow),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True, default=datetime.utcnow),
        sa.Column("user_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_competitions_id"), "competitions", ["id"], unique=False)
    op.create_table(
        "entry",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("topic", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), nullable=True),
        sa.Column("is_deleted", sa.BOOLEAN(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True, default=datetime.utcnow),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True, default=datetime.utcnow),
        sa.Column("competition_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_entry_id"), "entry", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_entry_id"), table_name="entry")
    op.drop_table("entry")
    op.drop_index(op.f("ix_competitions_id"), table_name="competitions")
    op.drop_table("competitions")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
